name: 🐞 Fehler melden
description: Einen Fehler in OstseeBit Tools melden.
labels: ['bug', 'triage']
body:
  - type: markdown
    attributes:
      value: |
        Danke, dass du dir die Zeit nimmst, einen Fehler in OstseeBit Tools zu melden.

  - type: textarea
    id: bug-description
    attributes:
      label: Fehlerbeschreibung
      description: Beschreibe den Fehler kurz und eindeutig. Falls du bereits einen Pull Request dazu planst, kannst du das hier ebenfalls angeben.
      placeholder: Was funktioniert nicht wie erwartet?
    validations:
      required: true

  - type: textarea
    id: what-happened
    attributes:
      label: Tatsächliches und erwartetes Verhalten
      description: Beschreibe, was passiert ist und welches Verhalten du erwartet hast. Screenshots können hier eingefügt werden.
      placeholder: Tatsächliches Verhalten und erwartetes Ergebnis
    validations:
      required: true

  - type: textarea
    id: version
    attributes:
      label: System- und Versionsinformationen
      description: Gib Browser, Betriebssystem und nach Möglichkeit die verwendete OstseeBit-Tools-Version bzw. den Commit an. Für Systeminformationen kann optional `npx envinfo --system --browsers` verwendet werden.
    validations:
      required: true

  - type: dropdown
    id: app-type
    attributes:
      label: Wo tritt der Fehler auf?
      options:
        - OstseeBit Tools
        - Self-Hosting
        - Andere Installation oder Umgebung
    validations:
      required: true
